### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#48]
Rename the repository to the new store name "Rebble Store", preferably "RebbleStore".

**Comment by Zetaphor** [comment]
Is it just my linux bias, or does anyone else have a vote for a lowercase style repo name?
ie: rebble-store

**Comment by ishotjr** [comment]
+1 for LC; `rebble-store`? :bowtie:

**Comment by sGerli** [comment]
Ok

**Comment by sGerli** [comment]
But I don't have admin privileges on this repo so I need @ishotjr to do it.

**Comment by ishotjr** [comment]
[Renamed](https://github.com/pebble-dev/rebble-store)!  Don't forget to update remotes, `gh-pages` links (I'll take care of `rebble.io`), etc. :bowtie:

**Comment by ishotjr** [comment]
FYI I added a *new* https://github.com/pebble-dev/The-Panic-Store repo whose description directs users to the new location, plus added `gh-pages` w/ quick JS redirects so that existing links (e.g. in blog posts that we don't have control over) will continue to work. :bowtie: 

I'm not sure if the @github bot on Discord will still work - it "should" since the Webhooks are still in place - but LMK if it needs re-setting up etc. :bowtie:

**Comment by ishotjr** [comment]
@sGerli FYI re-added the repo to `#appstore`:

`!dbg add pebble-dev/rebble-store`

:bowtie:
