### ISSUE TITLE
Create Backend

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#5]
Includes:

- [x] Decide Backend Language.
- [ ] Connection to app, category, screenshots, author DB.
- [ ] Make a new dev-portal in which authors can upload .pbw, screenshots, app/watchface banners, app icons, descriptions, and manage their app versions.
- [ ] Add moderators that can moderate the App Store and its submissions.
- [ ] Check that .pbw aren't masked viruses.
- [x]  Rest API
-  Probably there are more things that I forgot.

**Backend Language:** Go Lang

Extra Info:
- App banners have to be 720px x 320px (Original app store size).
- App Screenshots also have to be of their original size.
- Frontend will be single page with VUE JS

**Comment by ShawnBaek** [comment]
How about use parse-server as backend?

**Comment by KonradIT** [comment]
Here is how I frame it:

The store fetches a JSON list with the app names ([like this](https://gist.github.com/KonradIT/0d74b358cfd8c0ce801161e80efa01ae)), then it fetches the app UUID and generates from that the app-details page, I'll use @ardaozkal's mirror for a quick demo.

**Comment by okschlatter** [comment]
You could probably use SQL.

**Comment by Zetaphor** [comment]
I'm debating between putting up a poll, and simply starting with a set of technologies I choose.

We know we're going to need at least 3 things to make this stack happen:
* A client-side framework to do the heavy lifting
* A REST API on the server to provide data to the frontend
* A database to store all of this information

I'm personally in the camp of Vue for the frontend, Flask for the backend, and any SQL variant for the DB. Something like Redis could be useful in this context depending on what we're looking at in terms of scale and functional complexity.

Does anyone have any thoughts? Should I just throw up a poll? Who in the team is interested in working on this portion aside from me?

**Comment by torharrington** [comment]
if we have the original JSON could we use some document store like mongo or documentdb or something?

**Comment by moejay** [comment]
How about we set out to define REST APIs using swagger?

**Comment by moejay** [comment]
Also @sGerli , should we even look at CI now?

**Comment by sGerli** [comment]
Not yet

**Comment by TheTechmage** [comment]
@moejay At least with golang and what's been pushed up so far, I've found that [test2doc](https://github.com/adams-sarah/test2doc) will automatically create documentation in the API Blueprint format. I would've liked it if it generated swagger docs (due to how many tools can render swagger), but it was the only library that I could find that would use the comments within the code and actual API requests and responses to generate the documentation. If someone wanted to create some form of API list that the backend could mimick, that'd be great!

**Comment by moejay** [comment]
Oh nice, it generates blueprint, we should be able to add a build step to convert to swagger spec if need be a quick search, turned out [this](https://github.com/kminami/apib2swagger)

**Comment by TheTechmage** [comment]
We have split off the backend work into it's own repo. Further discussion should occur within that project's issue tracker.

Closing this issue since it is no longer relevant to the current repo.

P.S. Thanks for the tip @moejay, looks like that'll work! I've created a relevant ticket here: https://github.com/pebble-dev/rebblestore-api/issues/5
